### ISSUE TITLE
User specified by PUID/PGID is not being used

### ISSUE THREAD

**Issue by danthonywalker** [hotio/radarr#25]
I have the following compose service defined for radarr:
```
  radarr:
    image: ghcr.io/hotio/radarr:release-5.7.0.8882
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: ${RADARR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    networks:
      - proxy
    volumes:
      - radarr:/config
      - data:/data
```
However, when I try to, say, add a Root Folder, I get the following error:
```
Unable to add root folder

    Folder '/data/media/movies/' is not writable by user 'hotio'
```
Which is strange, why specify a PUID/PGID if it's not going to be used? The Docker logs even say it's using the user I want it to:
```
----------------------------------------------------------------------

ENVIRONMENT BASE

----------------------------------------------------------------------

PUID=10023

PGID=90075961
```
So I'm confused on the error...
