### ISSUE TITLE
Remember me does not work with hotio radarr image

### ISSUE THREAD

**Issue by l00d3r** [hotio/radarr#26]
Every time I restart the radarr container and after that refresh my radarr's webpage I'm logged out even though I have checked the Remember me checkbox...

I'm running my radarr instance with the following config:

```
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: loki
    ports:
      - 7878:7878
    environment:
      - PUID=1005
      - PGID=118
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/containers/radarr:/config
      - /data:/data
```

I tested the exact same config with linuxserver's image and there is no such issue there, I tried finding what the difference with your and their image was, but unfortunately I did not find anything.

I have the same issue with hotios sonarr image and not with linuxservers image, so looks like something deeper than just radarrs issue.

I have no basepaths, proxies or certificates in my setup and am accessing directly over ip and port.
